import {
  getIndexHtml,
  injectCssIntoHtml,
  injectDirIntoHtml,
} from '../src/assets';
import { KETCH_RTL_CSS } from '../src/assets/rtlCss';

const BASE_HTML = '<html>\n  <head>\n  </head>\n  <body></body>\n</html>';

describe('injectCssIntoHtml', () => {
  it('injects a style tag before </head>', () => {
    const result = injectCssIntoHtml(BASE_HTML, 'body { color: red; }');

    expect(result).toContain('<style>body { color: red; }</style>\n</head>');
  });

  it('returns html unchanged when css is empty or missing', () => {
    expect(injectCssIntoHtml(BASE_HTML)).toBe(BASE_HTML);
    expect(injectCssIntoHtml(BASE_HTML, '   ')).toBe(BASE_HTML);
  });
});

describe('injectDirIntoHtml', () => {
  it('sets the dir attribute on the document root', () => {
    expect(injectDirIntoHtml(BASE_HTML, 'ltr')).toContain('<html dir="ltr">');
  });

  it('injects the bundled RTL stylesheet when dir is rtl', () => {
    const result = injectDirIntoHtml(BASE_HTML, 'rtl');

    expect(result).toContain('<html dir="rtl">');
    expect(result).toContain(`<style>${KETCH_RTL_CSS}</style>\n</head>`);
  });

  it('does not inject the RTL stylesheet for other directions', () => {
    expect(injectDirIntoHtml(BASE_HTML, 'ltr')).not.toContain(
      "[dir='rtl'] #ketch-banner"
    );
    expect(injectDirIntoHtml(BASE_HTML, 'auto')).not.toContain(
      "[dir='rtl'] #ketch-banner"
    );
  });

  it('returns html unchanged when dir is not provided', () => {
    expect(injectDirIntoHtml(BASE_HTML)).toBe(BASE_HTML);
  });

  it('applies to the html generated by getIndexHtml', () => {
    const html = getIndexHtml({
      organizationCode: 'acme',
      propertyCode: 'prop',
    });
    const result = injectDirIntoHtml(html, 'rtl');

    expect(result).toContain('<html dir="rtl">');
    expect(result).toContain("[dir='rtl'] #ketch-banner");
  });
});
