import {
  getIndexHtml,
  injectCssIntoHtml,
  injectDirIntoHtml,
} from '../src/assets';

const BASE_HTML = '<html>\n  <head>\n  </head>\n  <body></body>\n</html>';

describe('injectCssIntoHtml', () => {
  it('injects a style tag before </head>', () => {
    const result = injectCssIntoHtml(BASE_HTML, 'body { color: red; }');

    expect(result).toContain('<style>body { color: red; }</style>\n</head>');
  });

  it('returns html unchanged when css is empty or missing', () => {
    expect(injectCssIntoHtml(BASE_HTML)).toBe(BASE_HTML);
    expect(injectCssIntoHtml(BASE_HTML, '   ')).toBe(BASE_HTML);
  });
});

describe('injectDirIntoHtml', () => {
  it('sets the dir attribute on the document root', () => {
    expect(injectDirIntoHtml(BASE_HTML, 'rtl')).toContain('<html dir="rtl">');
    expect(injectDirIntoHtml(BASE_HTML, 'ltr')).toContain('<html dir="ltr">');
  });

  it('returns html unchanged when dir is not provided', () => {
    expect(injectDirIntoHtml(BASE_HTML)).toBe(BASE_HTML);
  });

  it('applies to the html generated by getIndexHtml', () => {
    const html = getIndexHtml({
      organizationCode: 'acme',
      propertyCode: 'prop',
    });

    expect(injectDirIntoHtml(html, 'rtl')).toContain('<html dir="rtl">');
  });
});
