name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: npm run lint

      - name: Typecheck files
        run: npm run typecheck

      - name: Build library
        run: npm run all

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: ketch-com

      - name: Publish
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
